--- 
clone: 
  depth: 1
kind: pipeline
name: silont-project
steps: 
  - 
    commands:
      - "apt update -qqy && apt install -qqy openjdk-11-jre-headless"
      - "curl -OsSL https://github.com/azrim/script/raw/master/kernel/drone.sh"
      - "bash drone.sh"
    environment: 
      TOKEN: 
        from_secret: BOT_API_KEY
    image: fadlyas/kernel_dockerfile:latest
    name: azrim
    trigger: 
      branch: 
        - raphtalia
        
