--- 
clone: 
  depth: 1
kind: pipeline
name: silont-project
steps: 
  - 
    commands:
      - "bash build.sh"
    image: azrim89/kurumi:rev-3
    name: azrim
    trigger: 
      branch: 
        - new
        
